// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk2Rn5YQKwyYDQutcQF0tAdrF5pPhHldM',
    appId: '1:920570880842:web:2e2381f62b08bdec9c97b3',
    messagingSenderId: '920570880842',
    projectId: 'xml-validator-72a10',
    authDomain: 'xml-validator-72a10.firebaseapp.com',
    storageBucket: 'xml-validator-72a10.firebasestorage.app',
    measurementId: 'G-JPEKXLP2H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARxEI4rsDILnV1jsMM4OWCNg8uuY3pueE',
    appId: '1:920570880842:android:eb5c15aeec2e34029c97b3',
    messagingSenderId: '920570880842',
    projectId: 'xml-validator-72a10',
    storageBucket: 'xml-validator-72a10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfKac83yjvT-4D9SkJ3KF4ZUV_6q7QwE0',
    appId: '1:920570880842:ios:293d1f9fbd76a79f9c97b3',
    messagingSenderId: '920570880842',
    projectId: 'xml-validator-72a10',
    storageBucket: 'xml-validator-72a10.firebasestorage.app',
    iosBundleId: 'com.example.fiscalValidator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfKac83yjvT-4D9SkJ3KF4ZUV_6q7QwE0',
    appId: '1:920570880842:ios:293d1f9fbd76a79f9c97b3',
    messagingSenderId: '920570880842',
    projectId: 'xml-validator-72a10',
    storageBucket: 'xml-validator-72a10.firebasestorage.app',
    iosBundleId: 'com.example.fiscalValidator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk2Rn5YQKwyYDQutcQF0tAdrF5pPhHldM',
    appId: '1:920570880842:web:2614e5d53be6d0099c97b3',
    messagingSenderId: '920570880842',
    projectId: 'xml-validator-72a10',
    authDomain: 'xml-validator-72a10.firebaseapp.com',
    storageBucket: 'xml-validator-72a10.firebasestorage.app',
    measurementId: 'G-9V1GNN3GW7',
  );
}
